apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookings-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookingservice
  template:
    metadata:
      labels:
        app: bookingservice
    spec:
      containers:
        - name: bookingservice
          image: lisichk0/bookingservice:latest
